http:
  host: "localhost"
  port: 8080
app:
  datacenter_id: 0
  machine_id: 0
secret:
  secret_key: secretKey
auth:
  jwtAccessSecret: "access-secret"
  jwtRefreshSecret: "refresh-secret"
  jwtAccessExpiresIn: "5m"
  jwtRefreshExpiresIn: "7d"
db:
  mysql:
    url: "localhost"
    port: 3306
    database: "short_links"
    username: "short_links"
    password: "short_links"
    synchronize: true

  redis:
    host: "localhost"
    port: 6379
    db: 0
